name: Run GitHub Action

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Also runs on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 23f3003179@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Display Current Time
        run: date
